name = "repo-1"
compatibility_date = "2026-06-16"
compatibility_flags = ["nodejs_compat"]
main = ".vercel/output/static/_worker.js/index.js"

[assets]
directory = ".vercel/output/static"
binding = "ASSETS"

[[kv_namespaces]]
binding = "busquedas"
id = "ac6d4085914647e3a76a59b3c39a729c"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "repo-1"

[images]
binding = "IMAGES"

[observability]
enabled = true

[[routes]]
pattern = "starwars.esign.company"
custom_domain = true
